version: "3.8"

services:
  postgres:
    image: postgres:16
    env_file: .env
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: portgasDace
      POSTGRES_DB: lms
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    networks:
      - lms

networks:
  lms:
    driver: bridge
